name: Development CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions: 
  id-token: write
  contents: read

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION  }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/tf-role

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Run terraform init
        run: terraform init

      - name: Run terraform format
        run: terraform fmt -check

      - name: Run terraform plan
        run: terraform plan -var-file=dev.tfvars
        env:
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_environment: "dev"
      
      - name: Run terraform apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: terraform apply -auto-approve -var-file=dev.tfvars
        env:
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_environment: "dev"